version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.10
    restart: always
    depends_on: 
    - postgres
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: ${POSTGRES_HOST}
            port: 5432
            database: ${POSTGRES_DB}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            migration: true
  postgres:
    ports:
    - "5432:5432"
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~